Repository pingcap/monitoring, pull requests merged in 2024-10, with the labels that each got.

#602 fix: remove deprecated binlog component
  monitoring.yaml
Labels: lgtm, approved, size/XS

#607 Update renovate.json
  .github/renovate.json
Labels: lgtm, approved, size/XS

#608 chore(deps): bump go to 1.23 and bump go mods
  cmd/main.go
  cmd/monitoring.go
  go.mod
  go.sum
  monitor-snapshot/v4.0.0-beta.1/ansible-monitor.tar.gz
  monitor-snapshot/v4.0.0-beta.1/operator/Dockerfile
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/binlog.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/lightning.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/nodes.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/overview.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/pd.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/pods.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tidb.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_details.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_summary.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_trouble_shooting.json
  monitor-snapshot/v4.0.0-beta.1/operator/datasources/k8s-datasource.yaml
  monitor-snapshot/v4.0.0-beta.1/operator/datasources/tidb-cluster-datasource.yaml
  monitor-snapshot/v4.0.0-beta.1/operator/init.sh
  monitor-snapshot/v4.0.0-beta.1/operator/rules/binlog.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/lightning.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/pd.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tidb.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tikv.accelerate.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tikv.rules.yml
  pkg/common/utils.go
Labels: size/XXL, lgtm, approved

#625 sec: bump some golang mod for security
  cmd/main.go
  go.mod
  go.sum
  pkg/operator/rules.go
  reload/server/bizlogic/server.go
Labels: size/XXL, lgtm, approved, do-not-merge/hold

#632 build: update go.mod
  go.mod
Labels: lgtm, approved, size/XS

#639 fix: fix rules parse with prome model and YAML v3
  cmd/main.go
  pkg/operator/rules.go
Labels: lgtm, approved, size/S

#643 Fix/rule-marshal-unmarshal
  cmd/main.go
  cmd/monitoring.go
  go.mod
  pkg/operator/rules.go
Labels: lgtm, approved, size/S
