Repository pingcap/monitoring, pull requests merged in 2024-03, with the labels that each got.

#310 ci: fix prepare_prometheus.sh
  scripts/prepare_prometheus.sh
Labels: lgtm, approved, size/XS

#317 Update prepare_prometheus.sh
  scripts/prepare_prometheus.sh
Labels: lgtm, approved, size/XS

#324 Cd/add build grafana script
  .gitignore
  Makefile
  scripts/build_tiup_grafana.sh
Labels: lgtm, approved, size/S

#329 ci: control the third-party versions with dependencies
  dependencies.yaml
  scripts/build_tiup_grafana.sh
  scripts/prepare_prometheus.sh
Labels: lgtm, approved, size/S

#334 ci(scripts): fix prepare_prometheus.sh script
  scripts/prepare_prometheus.sh
Labels: lgtm, approved

#335 ci(scripts): fix prepare_prometheus.sh script
  scripts/prepare_prometheus.sh
Labels: lgtm, approved, size/XS

#338 ci: fix grafana script
  scripts/build_tiup_grafana.sh
Labels: lgtm, approved, size/XS

#339 Update renovate.json
  .github/renovate.json
Labels: lgtm, approved, size/XS

#340 ci: fix renovate config
  .github/renovate.json
  dependencies.yaml
Labels: lgtm, approved, size/XS

#359 chore: make building reproducibe
  .github/renovate.json
  dependencies.yaml
  scripts/build_tiup_grafana.sh
  scripts/prepare_prometheus.sh
Labels: lgtm, approved, size/M

#363 Update dependencies.yaml
  dependencies.yaml
Labels: lgtm, approved

#365 update dashboard to add tiproxy
  pkg/operator/dashboards.go
Labels: lgtm, approved, size/XS

#377 chore: update monitor-snapshot
  monitor-snapshot/release-7.6/ansible-monitor.tar.gz
  monitor-snapshot/release-7.6/operator/Dockerfile
  monitor-snapshot/release-7.6/operator/dashboards/DM-Monitor-Professional.json
  monitor-snapshot/release-7.6/operator/dashboards/DM-Monitor-Standard.json
  monitor-snapshot/release-7.6/operator/dashboards/TiCDC-Monitor-Summary.json
  monitor-snapshot/release-7.6/operator/dashboards/binlog.json
  monitor-snapshot/release-7.6/operator/dashboards/lightning.json
  monitor-snapshot/release-7.6/operator/dashboards/nodes.json
  monitor-snapshot/release-7.6/operator/dashboards/overview.json
  monitor-snapshot/release-7.6/operator/dashboards/pd.json
  monitor-snapshot/release-7.6/operator/dashboards/performance_overview.json
  monitor-snapshot/release-7.6/operator/dashboards/pods.json
  monitor-snapshot/release-7.6/operator/dashboards/ticdc.json
  monitor-snapshot/release-7.6/operator/dashboards/tidb.json
  monitor-snapshot/release-7.6/operator/dashboards/tidb_resource_control.json
  monitor-snapshot/release-7.6/operator/dashboards/tidb_runtime.json
  monitor-snapshot/release-7.6/operator/dashboards/tiflash_proxy_details.json
  monitor-snapshot/release-7.6/operator/dashboards/tiflash_proxy_summary.json
  monitor-snapshot/release-7.6/operator/dashboards/tiflash_summary.json
  monitor-snapshot/release-7.6/operator/dashboards/tikv-cdc.json
  monitor-snapshot/release-7.6/operator/dashboards/tikv_details.json
  monitor-snapshot/release-7.6/operator/dashboards/tikv_summary.json
  monitor-snapshot/release-7.6/operator/dashboards/tikv_trouble_shooting.json
  monitor-snapshot/release-7.6/operator/datasources/dm-cluster-datasource.yaml
  monitor-snapshot/release-7.6/operator/datasources/k8s-datasource.yaml
  monitor-snapshot/release-7.6/operator/datasources/tidb-cluster-datasource.yaml
  monitor-snapshot/release-7.6/operator/init.sh
  monitor-snapshot/release-7.6/operator/rules/binlog.rules.yml
  monitor-snapshot/release-7.6/operator/rules/lightning.rules.yml
  monitor-snapshot/release-7.6/operator/rules/pd.rules.yml
  monitor-snapshot/release-7.6/operator/rules/ticdc.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tidb.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tiflash.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tikv-cdc.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tikv.accelerate.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tikv.rules.yml
  monitor-snapshot/release-7.6/operator/rules/tiproxy.rules.yml
Labels: dependencies, size/XXL, lgtm, approved

#378 chore: update snapshot
  monitor-snapshot/release-7.5/ansible-monitor.tar.gz
  monitor-snapshot/release-7.5/operator/dashboards/ticdc.json
  monitor-snapshot/release-7.5/operator/dashboards/tidb.json
  monitor-snapshot/v4.0.0-beta.1/ansible-monitor.tar.gz
  monitor-snapshot/v4.0.0-beta.1/operator/Dockerfile
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/binlog.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/lightning.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/nodes.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/overview.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/pd.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/pods.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tidb.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_details.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_summary.json
  monitor-snapshot/v4.0.0-beta.1/operator/dashboards/tikv_trouble_shooting.json
  monitor-snapshot/v4.0.0-beta.1/operator/datasources/k8s-datasource.yaml
  monitor-snapshot/v4.0.0-beta.1/operator/datasources/tidb-cluster-datasource.yaml
  monitor-snapshot/v4.0.0-beta.1/operator/init.sh
  monitor-snapshot/v4.0.0-beta.1/operator/rules/binlog.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/lightning.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/pd.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tidb.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tikv.accelerate.rules.yml
  monitor-snapshot/v4.0.0-beta.1/operator/rules/tikv.rules.yml
Labels: dependencies, size/XXL, lgtm, approved
